version: '3'
services:
  maxilog-postgresql:
    image: postgres:11.5
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresDB:/var/lib/postresql/data
      - ./data/postgres-entrypoint:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=maxilog-default
      - POSTGRES_USER=maxilog-default-user
      - POSTGRES_PASSWORD=maxilog-default-password

