create sequence hibernate_sequence;

create table oauth_client_details
(
    id            bigint generated by default as identity
        constraint oauth_client_details_pkey
            primary key,
    client_id     varchar(255) not null
        constraint uk_3my6lp6ttga6hhwtsutscqset
            unique,
    client_secret varchar(255),
    grant_types   varchar(255),
    scopes        varchar(255)
);

INSERT INTO oauth_client_details (id, client_id, client_secret, grant_types, scopes) VALUES (1, 'client', '$2a$10$jDZXz.UGGyaf9uU0Rm2cCusgLOA4u33vV0YJTXnAQru4Fi5igoEpO', 'refresh_token, password, client_credentials', 'web');
INSERT INTO oauth_client_details (id, client_id, client_secret, grant_types, scopes) VALUES (2, 'client2', '$2a$10$BsW5REJSMXPm7gz.GHAV5.5gYMoIgW35u0MwU7AZh0AZ7tQJJjp6m', 'implicit, refresh_token, authorization_code', 'web');


create table oauth_user_details
(
    id             bigint generated by default as identity (maxvalue 2147483647)
        constraint users_pkey
            primary key,
    email          varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    email_verified boolean      not null,
    name           varchar(255) not null,
    password       varchar(255),
    image_url      text
);

INSERT INTO oauth_user_details (id, email, email_verified, name, password, image_url) VALUES (1, 'maxilog@gmail.com', false, 'maxilog', '$2a$10$QReTnHo.1EOgcjsC2go5meik4nqJvdbtBVx9gyhaClxrIzth3pjKK', null);
INSERT INTO oauth_user_details (id, email, email_verified, name, password, image_url) VALUES (7, 'mzarzis7@yahoo.fr', false, 'Mossab Zarzis', null, '16609');
INSERT INTO oauth_user_details (id, email, email_verified, name, password, image_url) VALUES (9, 'mahat.mossab@gmail.com', true, 'Mossab Mahat', null, '16625');


create table oauth_access_token
(
    token_id          varchar(256),
    token             bytea,
    authentication_id text not null
        constraint oauth_access_token_pkey
            primary key,
    user_name         varchar(256),
    client_id         varchar(256),
    authentication    bytea,
    refresh_token     varchar(256)
);

create table oauth_refresh_token
(
    token_id       varchar(256),
    token          bytea,
    authentication bytea
);


create table oauth2_authorized_client
(
    client_registration_id  varchar(100)                            not null,
    principal_name          varchar(200)                            not null,
    access_token_type       varchar(100)                            not null,
    access_token_value      bytea                                   not null,
    access_token_issued_at  timestamp                               not null,
    access_token_expires_at timestamp                               not null,
    access_token_scopes     varchar(1000) default NULL::character varying,
    refresh_token_value     bytea,
    refresh_token_issued_at timestamp,
    created_at              timestamp     default CURRENT_TIMESTAMP not null,
    constraint oauth2_authorized_client_pkey
        primary key (client_registration_id, principal_name)
);



